# Site settings
title: Blong
email: tseeker.china@gmail.com
description: "壁龙 blong 壁龙洁具 壁龙卫浴 洁具 卫浴"
baseurl: ""
url: "http://blong.wang"

markdown: kramdown

#paginate: 4
#paginate_path: "blog/page:num"
